/**<
 * @brief Utilities for implementing USB audio devices
 */

#ifndef USB_AUDIO_H
#define USB_AUDIO_H

//------------------------------------------------------------------------------
// Types
//------------------------------------------------------------------------------

typedef enum {
  USB_AUDIO_CAT_UNDEF = 0x00,
  USB_AUDIO_CAT_DESKTOP_SPEAKER = 0x01,
  USB_AUDIO_CAT_HOME_THEATER = 0x02,
  USB_AUDIO_CAT_MICROPHONE = 0x03,
  USB_AUDIO_CAT_HEADSET = 0x04,
  USB_AUDIO_CAT_TELEPHONE = 0x05,
  USB_AUDIO_CAT_CONVERTER = 0x06,
  USB_AUDIO_CAT_RECORDER = 0x07,
  USB_AUDIO_CAT_IO_BOX = 0x08,
  USB_AUDIO_CAT_MUSICAL_INSTRUMENT = 0x09,
  USB_AUDIO_CAT_PRO_AUDIO = 0x0A,
  USB_AUDIO_CAT_AV = 0x0B,
  USB_AUDIO_CAT_CONTROL_PANEL = 0x0C,
  USB_AUDIO_CAT_OTHER = 0xFF,
} UsbAudioFunctionCategoryType;

typedef enum {
  USB_AUDIO_CS_UNDEF = 0x20,
  USB_AUDIO_CS_DEV = 0x21,
  USB_AUDIO_CS_CONFIG = 0x22,
  USB_AUDIO_CS_STRING = 0x23,
  USB_AUDIO_CS_IFACE = 0x24,
  USB_AUDIO_CS_EPT = 0x25,
} UsbAudioClassDescType;

typedef enum {
  USB_AUDIO_AC_DESC_UNDEF = 0x00,
  USB_AUDIO_AC_DESC_HEADER = 0x01,
  USB_AUDIO_AC_DESC_INPUT_TERM = 0x02,
  USB_AUDIO_AC_DESC_OUTPUT_TERM = 0x03,
  USB_AUDIO_AC_DESC_MIXER_UNIT = 0x04,
  USB_AUDIO_AC_DESC_SELECTOR_UNIT = 0x05,
  USB_AUDIO_AC_DESC_FEATURE_UNIT = 0x06,
  USB_AUDIO_AC_DESC_EFFECT_UNIT = 0x07,
  USB_AUDIO_AC_DESC_PROCESSING_UNIT = 0x08,
  USB_AUDIO_AC_DESC_EXTENSION_UNIT = 0x09,
  USB_AUDIO_AC_DESC_CLOCK_SOURCE = 0x0A,
  USB_AUDIO_AC_DESC_CLOCK_SELECTOR = 0x0B,
  USB_AUDIO_AC_DESC_CLOCK_MULTIPLIER = 0x0C,
  USB_AUDIO_AC_DESC_SAMPLE_RATE_CONVERTER = 0x0D,
} UsbAudioCtrlDescSubType;

typedef enum {
  USB_AUDIO_AI_DESC_UNDEF = 0x00,
  USB_AUDIO_AI_DESC_GENERAL = 0x01,
  USB_AUDIO_AI_DESC_FORMAT_TYPE = 0x02,
  USB_AUDIO_AI_DESC_ENCODER = 0x03,
  USB_AUDIO_AI_DESC_DECODER = 0x04,
} UsbAudioIfaceDescSubType;

typedef enum {
  USB_AUDIO_EFFECT_UNDEF = 0x00,
  USB_AUDIO_EFFECT_PARAM_EQ_SECTION = 0x01,
  USB_AUDIO_EFFECT_REVERBERATION = 0x02,
  USB_AUDIO_EFFECT_MOD_DELAY = 0x03,
  USB_AUDIO_EFFECT_DYN_RANGE_COMP = 0x04,
} UsbAudioEffectUnitType;

typedef enum {
  USB_AUDIO_PROCESS_UNDEF = 0x00,
  USB_AUDIO_PROCESS_UP_DOWN_MIX = 0x01,
  USB_AUDIO_PROCESS_DOLBY_PROLOGIC = 0x02,
  USB_AUDIO_PROCESS_STEREO_EXTENDER = 0x03,
} UsbAudioProcessingUnitType;

typedef enum {
  USB_AUDIO_AEP_DESC_UNDEF = 0x00,
  USB_AUDIO_AEP_DESC_GENERAL = 0x01,
} UsbAudioEptDescSubType;

typedef enum {
  USB_AUDIO_REQ_UNDEF = 0x00,
  USB_AUDIO_REQ_CUR = 0x01,
  USB_AUDIO_REQ_RANGE = 0x02,
  USB_AUDIO_REQ_MEM = 0x03,
} UsbAudioRequestIdType;

typedef enum {
  USB_AUDIO_ENCODER_UNDEF = 0x00,
  USB_AUDIO_ENCODER_OTHER = 0x01,
  USB_AUDIO_ENCODER_MPEG = 0x02,
  USB_AUDIO_ENCODER_AC3 = 0x03,
  USB_AUDIO_ENCODER_WMA = 0x04,
  USB_AUDIO_ENCODER_DTS = 0x05,
} UsbAudioEncoderType;

typedef enum {
  UBS_AUDIO_DECODER_UNDEF = 0x00,
  USB_AUDIO_DECODER_OTHER = 0x01,
  USB_AUDIO_DECODER_MPEG = 0x02,
  USB_AUDIO_DECODER_AC3 = 0x03,
  USB_AUDIO_DECODER_WMA = 0x04,
  USB_AUDIO_DECODER_DTS = 0x05,
} UsbAudioDecoderType;

typedef enum {
  USB_AUDIO_CLK_SRC_CTRL_UNDEF = 0x00,
  USB_AUDIO_CLK_SRC_CTRL_SAM_FREQ = 0x01,
  USB_AUDIO_CLK_SRC_CTRL_CLOCK_VALID = 0x02,
} UsbAudioClkSrcCtrlType;

typedef enum {
  USB_AUDIO_CLK_SEL_CTRL_UNDEF = 0x00,
  USB_AUDIO_CLK_SEL_CTRL_SELECTOR = 0x01,
} UsbAudioClkSelCtrlType;

typedef enum {
  USB_AUDIO_CLK_MUL_CTRL_UNDEF = 0x00,
  USB_AUDIO_CLK_MUL_CTRL_NUMERATOR = 0x01,
  USB_AUDIO_CLK_MUL_CTRL_DENOMINATOR = 0x02,
} UsbAudioClkMulCtrlType;

typedef enum {
  USB_AUDIO_TERM_CTRL_UNDEF = 0x00,
  USB_AUDIO_TERM_CTRL_COPY_PROTECT = 0x01,
  USB_AUDIO_TERM_CTRL_CONNECTOR = 0x02,
  USB_AUDIO_TERM_CTRL_OVERLOAD = 0x03,
  USB_AUDIO_TERM_CTRL_CLUSTER = 0x04,
  USB_AUDIO_TERM_CTRL_UNDERFLOW = 0x05,
  USB_AUDIO_TERM_CTRL_OVERLFLOW = 0x06,
  USB_AUDIO_TERM_CTRL_LATENCY = 0x07,
} UsbAudioTermCtrlType;

typedef enum {
  USB_AUDIO_MIXER_CTRL_UNDEF = 0x00,
  USB_AUDIO_MIXER_CTRL_MIXER = 0x01,
  USB_AUDIO_MIXER_CTRL_CLUSTER = 0x02,
  USB_AUDIO_MIXER_CTRL_UNDERFLOW = 0x03,
  USB_AUDIO_MIXER_CTRL_OVERFLOW = 0x04,
  USB_AUDIO_MIXER_CTRL_LATENCY = 0x05,
} UsbAudioMixerCtrlType;

typedef enum {
  USB_AUDIO_SEL_CTRL_UNDEF = 0x00,
  USB_AUDIO_SEL_CTRL_SELECTOR = 0x01,
  USB_AUDIO_SEL_CTRL_LATENCY = 0x02,
} UsbAudioSelCtrlType;

typedef enum {
  USB_AUDIO_FEAT_CTRL_UNDEF = 0x00,
  USB_AUDIO_FEAT_CTRL_MUTE = 0x01,
  USB_AUDIO_FEAT_CTRL_VOLUME = 0x02,
  USB_AUDIO_FEAT_CTRL_BASS = 0x03,
  USB_AUDIO_FEAT_CTRL_MID = 0x04,
  USB_AUDIO_FEAT_CTRL_TREBLE = 0x05,
  USB_AUDIO_FEAT_CTRL_GRAPH_EQ = 0x06,
  USB_AUDIO_FEAT_CTRL_AUTO_GAIN = 0x07,
  USB_AUDIO_FEAT_CTRL_DELAY = 0x08,
  USB_AUDIO_FEAT_CTRL_BASS_BOST = 0x09,
  USB_AUDIO_FEAT_CTRL_LOUDNESS = 0x0A,
  USB_AUDIO_FEAT_CTRL_INPUT_GAIN = 0x0B,
  USB_AUDIO_FEAT_CTRL_INPUT_GAIN_PAD = 0x0C,
  USB_AUDIO_FEAT_CTRL_PHASE_INVERTER = 0x0D,
  USB_AUDIO_FEAT_CTRL_UNDERFLOW = 0x0E,
  USB_AUDIO_FEAT_CTRL_OVERFLOW = 0x0F,
  USB_AUDIO_FEAT_CTRL_LATENCY = 0x10,
} UsbAudioFeatCtrlType;

typedef enum {
  USB_AUDIO_PARA_EQ_CTRL_UNDEF = 0x00,
  USB_AUDIO_PARA_EQ_CTRL_ENABLE = 0x01,
  USB_AUDIO_PARA_EQ_CTRL_CENTERFREQ = 0x02,
  USB_AUDIO_PARA_EQ_CTRL_QFACTOR = 0x03,
  USB_AUDIO_PARA_EQ_CTRL_GAIN = 0x04,
  USB_AUDIO_PARA_EQ_CTRL_UNDEFLOW = 0x05,
  USB_AUDIO_PARA_EQ_CTRL_OVERFLOW = 0x06,
  USB_AUDIO_PARA_EQ_CTRL_LATENCY = 0x07,
} UsbAudioParaEqCtrlType;

typedef enum {
  USB_AUDIO_REVERB_CTRL_UNDEF = 0x00,
  USB_AUDIO_REVERB_CTRL_ENABLE = 0x01,
  USB_AUDIO_REVERB_CTRL_TYPE = 0x02,
  USB_AUDIO_REVERB_CTRL_LEVEL = 0x03,
  USB_AUDIO_REVERB_CTRL_TIME = 0x04,
  USB_AUDIO_REVERB_CTRL_FEEDBACK = 0x05,
  USB_AUDIO_REVERB_CTRL_PREDELAY = 0x06,
  USB_AUDIO_REVERB_CTRL_DENSITY = 0x07,
  USB_AUDIO_REVERB_CTRL_HIFREQ_CUTOFF = 0x08,
  USB_AUDIO_REVERB_CTRL_UNDERFLOW = 0x09,
  USB_AUDIO_REVERB_CTRL_OVERFLOW = 0x0A,
  USB_AUDIO_REVERB_CTRL_LATENCY = 0x0B,
} UsbAudioReverbCtrlType;

typedef enum {
  USB_AUDIO_MOD_DELAY_CTRL_UNDEF = 0x00,
  USB_AUDIO_MOD_DELAY_CTRL_ENABLE = 0x01,
  USB_AUDIO_MOD_DELAY_CTRL_BALANCE = 0x02,
  USB_AUDIO_MOD_DELAY_CTRL_RATE = 0x03,
  USB_AUDIO_MOD_DELAY_CTRL_DEPTH = 0x04,
  USB_AUDIO_MOD_DELAY_CTRL_TIME = 0x05,
  USB_AUDIO_MOD_DELAY_CTRL_FEEDBACK = 0x06,
  USB_AUDIO_MOD_DELAY_CTRL_UNDERFLOW = 0x07,
  USB_AUDIO_MOD_DELAY_CTRL_OVERFLOW = 0x08,
  USB_AUDIO_MOD_DELAY_CTRL_LATENCY = 0x09,
} UsbAudioModDelayCtrlType;

typedef enum {
  USB_AUDIO_DRC_CTRL_UNDEF = 0x00,
  USB_AUDIO_DRC_CTRL_ENABLE = 0x01,
  USB_AUDIO_DRC_CTRL_COMPRESSION_RATE = 0x02,
  USB_AUDIO_DRC_CTRL_MAXAMPL = 0x03,
  USB_AUDIO_DRC_CTRL_THRESHOLD = 0x04,
  USB_AUDIO_DRC_CTRL_ATTACK_TIME = 0x05,
  USB_AUDIO_DRC_CTRL_RELEASE_TIME = 0x06,
  USB_AUDIO_DRC_CTRL_UNDERFLOW = 0x07,
  USB_AUDIO_DRC_CTRL_OVERFLOW = 0x08,
  USB_AUDIO_DRC_CTRL_LATENCY = 0x09,
} UsbAudioDrcCtrlType;

typedef enum {
  USB_AUDIO_UP_DOWN_MIX_CTRL_UNDEF = 0x00,
  USB_AUDIO_UP_DOWN_MIX_CTRL_ENABLE = 0x01,
  USB_AUDIO_UP_DOWN_MIX_CTRL_MODE_SELECT = 0x02,
  USB_AUDIO_UP_DOWN_MIX_CTRL_CLUSTER = 0x03,
  USB_AUDIO_UP_DOWN_MIX_CTRL_UNDERFLOW = 0x04,
  USB_AUDIO_UP_DOWN_MIX_CTRL_OVERFLOW = 0x05,
  USB_AUDIO_UP_DOWN_MIX_CTRL_LATENCY = 0x06,
} UsbAudioUpDownMixCtrlType;

typedef enum {
  USB_AUDIO_DOLBY_PRO_CTRL_UNDEF = 0x00,
  USB_AUDIO_DOLBY_PRO_CTRL_ENABLE = 0x01,
  USB_AUDIO_DOLBY_PRO_CTRL_MODE_SELECT = 0x02,
  USB_AUDIO_DOLBY_PRO_CTRL_CLUSTER = 0x03,
  USB_AUDIO_DOLBY_PRO_CTRL_UNDERFLOW = 0x04,
  USB_AUDIO_DOLBY_PRO_CTRL_OVERFLOW = 0x05,
  USB_AUDIO_DOLBY_PRO_CTRL_LATENCY = 0x06,
} UsbAudioDolbyProCtrlType;

typedef enum {
  USB_AUDIO_STEREO_EXT_CTRL_UNDEF = 0x00,
  USB_AUDIO_STEREO_EXT_CTRL_ENABLE = 0x01,
  USB_AUDIO_STEREO_EXT_CTRL_WIDTH = 0x02,
  USB_AUDIO_STEREO_EXT_CTRL_UNDERFLOW = 0x03,
  USB_AUDIO_STEREO_EXT_CTRL_OVERFLOW = 0x04,
  USB_AUDIO_STEREO_EXT_CTRL_LATENCY = 0x05,
} UsbAudioStereoExtCtrlType;

typedef enum {
  USB_AUDIO_EXT_UNIT_CTRL_UNDEF = 0x00,
  USB_AUDIO_EXT_UNIT_CTRL_ENABLE = 0x01,
  USB_AUDIO_EXT_UNIT_CTRL_CLUSTER = 0x02,
  USB_AUDIO_EXT_UNIT_CTRL_UNDERFLOW = 0x03,
  USB_AUDIO_EXT_UNIT_CTRL_OVERFLOW = 0x04,
  USB_AUDIO_EXT_UNIT_CTRL_LATENCY = 0x05,
} UsbAudioExtUnitCtrlType;

typedef enum {
  USB_AUDIO_STREAM_CTRL_UNDEF = 0x00,
  USB_AUDIO_STREAM_CTRL_ACT_ALT_SETTING = 0x01,
  USB_AUDIO_STREAM_CTRL_VAL_ALT_SETTINGS = 0x02,
  USB_AUDIO_STREAM_CTRL_AUDIO_DATA_FORMAT = 0x03,
} UsbAudioStreamCtrlType;

typedef enum {
  USB_AUDIO_ENCODER_CTRL_UNDEF = 0x00,
  USB_AUDIO_ENCODER_CTRL_BIT_RATE = 0x01,
  USB_AUDIO_ENCODER_CTRL_QUALITY = 0x02,
  USB_AUDIO_ENCODER_CTRL_VBR = 0x03,
  USB_AUDIO_ENCODER_CTRL_TYPE = 0x04,
  USB_AUDIO_ENCODER_CTRL_UNDERFLOW = 0x05,
  USB_AUDIO_ENCODER_CTRL_OVERFLOW = 0x06,
  USB_AUDIO_ENCODER_CTRL_ENCODER_ERR = 0x07,
  USB_AUDIO_ENCODER_CTRL_PARAM1 = 0x08,
  USB_AUDIO_ENCODER_CTRL_PARAM2 = 0x09,
  USB_AUDIO_ENCODER_CTRL_PARAM3 = 0x0A,
  USB_AUDIO_ENCODER_CTRL_PARAM4 = 0x0B,
  USB_AUDIO_ENCODER_CTRL_PARAM5 = 0x0C,
  USB_AUDIO_ENCODER_CTRL_PARAM6 = 0x0D,
  USB_AUDIO_ENCODER_CTRL_PARAM7 = 0x0E,
  USB_AUDIO_ENCODER_CTRL_PARAM8 = 0x0F,
} UsbAudioEncoderCtrlType;

typedef enum {
  USB_AUDIO_MPEG_DECODER_CTRL_UNDEF = 0x00,
  USB_AUDIO_MPEG_DECODER_CTRL_DUAL_CHANNEL = 0x01,
  USB_AUDIO_MPEG_DECODER_CTRL_SECOND_STEREO = 0x02,
  USB_AUDIO_MPEG_DECODER_CTRL_MULTILINGUAL = 0x03,
  USB_AUDIO_MPEG_DECODER_CTRL_DYN_RANGE = 0x04,
  USB_AUDIO_MPEG_DECODER_CTRL_SCALING = 0x05,
  USB_AUDIO_MPEG_DECODER_CTRL_HILO_SCALING = 0x06,
  USB_AUDIO_MPEG_DECODER_CTRL_UNDERFLOW = 0x07,
  USB_AUDIO_MPEG_DECODER_CTRL_OVERFLOW = 0x08,
  USB_AUDIO_MPEG_DECODER_CTRL_DECODER_ERR = 0x09,
} UsbAudioMpegDecoderCtrlType;

typedef enum {
  USB_AUDIO_AC3_DECODER_CTRL_UNDEF = 0x00,
  USB_AUDIO_AC3_DECODER_CTRL_MODE = 0x01,
  USB_AUDIO_AC3_DECODER_CTRL_DYN_RANGE = 0x02,
  USB_AUDIO_AC3_DECODER_CTRL_SCALING = 0x03,
  USB_AUDIO_AC3_DECODER_CTRL_HILO_SCALING = 0x04,
  USB_AUDIO_AC3_DECODER_CTRL_UNDERFLOW = 0x05,
  USB_AUDIO_AC3_DECODER_CTRL_OVERFLOW = 0x06,
  USB_AUDIO_AC3_DECODER_CTRL_DECODER_ERR = 0x07,
} UsbAudioAc3DecoderCtrlType;

typedef enum {
  USB_AUDIO_WMA_DECODER_CTRL_UNDEF = 0x00,
  USB_AUDIO_WMA_DECODER_CTRL_UNDERFLOW = 0x01,
  USB_AUDIO_WMA_DECODER_CTRL_OVERFLOW = 0x02,
  USB_AUDIO_WMA_DECODER_CTRL_DECODER_ERR = 0x03,
} UsbAudioWmaDecoderCtrlType;

typedef enum {
  USB_AUDIO_DTS_DECODER_CTRL_UNDEF = 0x00,
  USB_AUDIO_DTS_DECODER_CTRL_UNDERFLOW = 0x01,
  USB_AUDIO_DTS_DECODER_CTRL_OVERFLOW = 0x02,
  USB_AUDIO_DTS_DECODER_CTRL_DECODER_ERR = 0x03,
} UsbAudioDtsDecoderCtrlType;

typedef enum {
  USB_AUDIO_EPT_CTRL_UNDEF = 0x00,
  USB_AUDIO_EPT_CTRL_PITCH = 0x01,
  USB_AUDIO_EPT_CTRL_DATA_OVERRUN = 0x02,
  USB_AUDIO_EPT_CTRL_DATA_UNDERRUN = 0x03,
} UsbAudioEptCtrlType;

//------------------------------------------------------------------------------
// Constants
//------------------------------------------------------------------------------

#define USB_CLASS_AUDIO 0x01

#define USB_SUBCLASS_AUDIO_UNDEF 0x00
#define USB_SUBCLASS_AUDIO_CONTROL 0x01
#define USB_SUBCLASS_AUDIO_STREAMING 0x02
#define USB_SUBCLASS_AUDIO_MIDISTREAMING 0x03

#define USB_PROTO_AUDIO_UNDEF 0x00
#define USB_PROTO_AUDIO_VERSION_02_00 0x20

#endif /* USB_AUDIO_H */
